name: Deploy Examples

on:
  push:
    branches:
      - main

jobs:
  deploy-examples:
    env:
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run examples:deploy